# Generated by Django 3.1.7 on 2021-03-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0003_canciones_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='canciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Caratulas'),
        ),
    ]
