# Generated by Django 3.1.7 on 2021-03-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0005_auto_20210314_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='usuario',
        ),
    ]
