# Generated by Django 3.1.7 on 2021-03-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Musica', '0006_remove_lista_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='usuariocreatedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usercreacion', to='auth.user'),
            preserve_default=False,
        ),
    ]
